on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v17
      - uses: cachix/cachix-action@v10
        with:
          name: carlthome
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - run: nix flake show
      - run: nix develop
      - run: poetry install
      - run: poetry run pytest
      - run: nix build
